### ISSUE TITLE
withdrawing tokens from a vault doesn't update the GUI

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.orderbook#663] opened 2024-05-21 19:40 UTC
## Motivation

When i withdraw tokens from a vault i want to see the GUI update

## Solution

Update the GUI when i withdraw tokens from a vault

**Comment by hardyjosh** [comment] 2024-09-16 10:19
dupe of #568

**Closed by hardyjosh** 2024-09-16 10:19 UTC
Labels: bug
