### ISSUE TITLE
inject an order owner into the context grid for simulations

### ISSUE THREAD

**Issue by thedavidmeister** [rainlanguage/rain.orderbook#670] opened 2024-05-24 03:42 UTC
## Motivation

Context grid is always 0 for order owner

## Solution

Inject an order owner

**Comment by hardyjosh** [comment] 2024-07-04 22:28
duplicate of https://github.com/rainlanguage/rain.orderbook/issues/649

**Closed by hardyjosh** 2024-07-04 22:28 UTC
Labels: bug
